# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
name: 'Default'
  vmImage: 'agentpoolvm1'
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Free Trial(162b6007-f67c-4d55-ac97-537956b0ab0b)'
    appType: 'webApp'
    appName: 'newpipelinetimer'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'
    deploymentMethod: 'auto'
steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
